// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.0
// source: cert-provider.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CertificateProviderClient is the client API for CertificateProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CertificateProviderClient interface {
	GetX509KeyPair(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error)
}

type certificateProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewCertificateProviderClient(cc grpc.ClientConnInterface) CertificateProviderClient {
	return &certificateProviderClient{cc}
}

func (c *certificateProviderClient) GetX509KeyPair(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error) {
	out := new(CertificateResponse)
	err := c.cc.Invoke(ctx, "/proto.CertificateProvider/GetX509KeyPair", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertificateProviderServer is the server API for CertificateProvider service.
// All implementations must embed UnimplementedCertificateProviderServer
// for forward compatibility
type CertificateProviderServer interface {
	GetX509KeyPair(context.Context, *CertificateRequest) (*CertificateResponse, error)
	mustEmbedUnimplementedCertificateProviderServer()
}

// UnimplementedCertificateProviderServer must be embedded to have forward compatible implementations.
type UnimplementedCertificateProviderServer struct {
}

func (UnimplementedCertificateProviderServer) GetX509KeyPair(context.Context, *CertificateRequest) (*CertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetX509KeyPair not implemented")
}
func (UnimplementedCertificateProviderServer) mustEmbedUnimplementedCertificateProviderServer() {}

// UnsafeCertificateProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CertificateProviderServer will
// result in compilation errors.
type UnsafeCertificateProviderServer interface {
	mustEmbedUnimplementedCertificateProviderServer()
}

func RegisterCertificateProviderServer(s grpc.ServiceRegistrar, srv CertificateProviderServer) {
	s.RegisterService(&CertificateProvider_ServiceDesc, srv)
}

func _CertificateProvider_GetX509KeyPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateProviderServer).GetX509KeyPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CertificateProvider/GetX509KeyPair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateProviderServer).GetX509KeyPair(ctx, req.(*CertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CertificateProvider_ServiceDesc is the grpc.ServiceDesc for CertificateProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CertificateProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CertificateProvider",
	HandlerType: (*CertificateProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetX509KeyPair",
			Handler:    _CertificateProvider_GetX509KeyPair_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cert-provider.proto",
}
